Differentiate between typing_extensions Sentinel and builtins sentinel
This is necessary as some properties, like __name__, are only available
on the builtin sentinel, not the typing_extensions Sentienl type.

This can be confirmed by running the following:

```
uv run -p 3.15 --with 'typing_extensions' python -c 'from typing_extensions import Sentinel; MISSING = Sentinel("MISSING"); print(MISSING.__name__)'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>     from typing_extensions import Sentinel; MISSING = Sentinel("MISSING"); MISSING.__name__
>                                                                            ^^^^^^^^^^^^^^^^
> AttributeError: 'Sentinel' object has no attribute '__name__'. Did you mean '.__ne__' instead of '.__name__'?

uv run -p 3.15 --with 'typing_extensions' python -c 'MISSING = sentinel("MISSING"); print(MISSING.__name__)'
> MISSING
```