enable the `dbg_macro` clippy rule (#4821)
Summary:
after connernilsen pointed out that i accidentally committed a `dbg!` macro, i wondered if there was a clippy rule to prevent such mistakes (see https://github.com/facebook/pyrefly/pull/4729#discussion_r3888493732). turns out there is!

note that enabling a rule globally seems to be nowhere near as straightforward as it is in most other linters, so i had to make some other changes:

- i had to set `workspace = true` in each package (https://github.com/rust-lang/rust-clippy/issues/16541#issuecomment-3881220162)
- i also had to move the existing `unexpected_cfgs` config out of the individual packages into the global config, to workaround https://github.com/rust-lang/cargo/issues/13157

Pull Request resolved: https://github.com/facebook/pyrefly/pull/4821

Test Plan:
intentionally inserted a `dbg!` macro and ran `cargo clippy`:

```
error: the `dbg!` macro is intended as a debugging tool
  --> crates/pyrefly_config/src/migration/error_codes.rs:72:9
   |
72 |         dbg!(&pyright_cfg.type_checking_mode);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.98.0/index.html#dbg_macro
   = note: requested on the command line with `-D clippy::dbg-macro`
help: remove the invocation before committing it to a version control system
   |
72 -         dbg!(&pyright_cfg.type_checking_mode);
72 +         &pyright_cfg.type_checking_mode;
   |

error: could not compile `pyrefly_config` (lib) due to 1 previous error
```

Reviewed By: samwgoldman

Differential Revision: D118959745

Pulled By: stroxler

fbshipit-source-id: fca410967f9edfeb2defa2225a5cad4dd8962ea1